name: six_pos
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.4+4

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  flutter_local_notifications: ^17.1.0
  path_provider: ^2.1.3
  image_picker: ^1.1.0
  fl_chart: ^0.67.0
  get: ^4.6.6
  flutter_switch: ^0.3.2
  timezone: ^0.9.2
  advance_pdf_viewer: ^2.0.1
  file_picker: ^8.0.2
  barcode_widget: ^2.0.4
  flutter_barcode_scanner: ^2.0.0
  permission_handler: ^11.3.1
  flutter_downloader: ^1.11.7
  fluttertoast: ^8.2.5
#  flutter_pos_printer_platform: ^1.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  flutter_spinkit: ^5.2.1
  typed_data: ^1.3.2
  http_parser: ^4.0.2
  path: ^1.9.0
  http: ^1.2.1
  dropdown_search: ^5.0.6
#  bluetooth_thermal_printer: ^0.0.6
  print_bluetooth_thermal: ^1.1.0
  esc_pos_utils_plus: ^2.0.3
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  pdf: ^3.10.8
  qr_flutter: ^4.0.0
  flutter_pdfview: ^1.2.1
  dio: ^5.7.0







dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/font/arabic/Cairo-SemiBold.ttf


fonts:
  - family: Arial
    fonts:
      - asset: assets/font/ARIAL.TTF
      - asset: assets/font/arabic/Cairo-SemiBold.ttf

  - family: Ubuntu
    fonts:
      - asset: assets/font/Ubuntu-Regular.ttf
        weight: 400
      - asset: assets/font/Ubuntu-Medium.ttf
        weight: 500
      - asset: assets/font/Ubuntu-Bold.ttf
        weight: 600
      - asset: assets/font/Ubuntu-Light.ttf
        weight: 300
      - asset: assets/font/Cairo-Regular.ttf
      - asset: assets/font/Tajawal-Black.ttf